### ISSUE TITLE
Get ids from stableid.json

### ISSUE THREAD

**Issue by Hanspagh** [ecly/TerranEasyBot#2]
We can use the following file ` ~/Documents/StarCraft II/stableid.json` for finding ids

**Comment by ecly** [comment]
I don't have that file. Is it the same as https://pastebin.com/KCwwLiQ1 ?

**Comment by Hanspagh** [comment]
Its the same ids, but not the same file :)

**Comment by Hanspagh** [comment]
Wont work on linux for now, new version of pysc2 will include ids so we will use that.
